### ISSUE TITLE
Make this repository public

### ISSUE THREAD

**Issue by luator** [intelligent-soft-robots/.github#1]
I just noticed that this repository already exists and even already contains a [pull request template](https://raw.githubusercontent.com/intelligent-soft-robots/.github/master/.github/pull_request_template.md?token=ACHGTAPYAZRCPM5RF2ZRE2DBJCJ5C).

It is currently not used, though.  I think this is because the repo is private.  So if I'm right, we just need to make this public then, the template would automatically be used for every repo inside this organisation.  Do you agree with this?

Also do you agree with the content of the current template?

**Comment by luator** [comment]
@vincentberenz FYI (I can only add one assignee here for some reason...)

**Comment by vincentberenz** [comment]
@luator @dtrb I just made the repo public

**Comment by luator** [comment]
Thanks.  I just verified, the template is working now.
